# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: books.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\tbookstore\"\x11\n\x0fGetBooksRequest\"2\n\x10GetBooksResponse\x12\x1e\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0f.bookstore.Book\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t2R\n\x0b\x42ookService\x12\x43\n\x08GetBooks\x12\x1a.bookstore.GetBooksRequest\x1a\x1b.bookstore.GetBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBOOKSREQUEST']._serialized_start=26
  _globals['_GETBOOKSREQUEST']._serialized_end=43
  _globals['_GETBOOKSRESPONSE']._serialized_start=45
  _globals['_GETBOOKSRESPONSE']._serialized_end=95
  _globals['_BOOK']._serialized_start=97
  _globals['_BOOK']._serialized_end=146
  _globals['_BOOKSERVICE']._serialized_start=148
  _globals['_BOOKSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
